  #Google Calendar API Configuration
google:
  client:
    client-id: 675767801724-n91rr99i2m0sh6hhhtcdiee3nf7ghsrk.apps.googleusercontent.com
    client-secret: 7JnJIJ5V-J1ueKPAD22uDFG9
    access-token-uri: https://www.googleapis.com/oauth2/v3/token
    user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent&response_type=code
    client-authentication-scheme: query
    scope: "https://www.googleapis.com/auth/calendar.events,https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email"
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    redirectUri: http://localhost:9000/auth/login
  resource:
    prefer-token-info: true

server:
  #  port: 8080
  port: 9000
  compression:
    enabled: true
    min-response-size: 200
    mime-types: "text/html, text/css, application/json"

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/vaCalendar?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      indent_output: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
      springframework: INFO

jwt:
  header: Authorization
  prefix: "Bearer"
  signing:
    key: As3cr3tkeiy_987654321